In [6]:
import os
import cv2
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from IPython.display import Image

In [7]:
import cv2
img1=cv2.imread('./oxygen.jpg',2|4)
cv2.namedWindow("imread", cv2.WINDOW_NORMAL)
cv2.imshow("imread", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import cv2
img1=cv2.imread('./oxygen.jpg', 0)
cv2.namedWindow("imread")
cv2.imshow("imread", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import cv2

# 读取图像
img1=cv2.imread('./oxygen.jpg',2|4)

# 创建窗口，允许用户调整大小
cv2.namedWindow("imread", cv2.WINDOW_AUTOSIZE)

# 显示图像
cv2.imshow("imread", img1)

# 等待按键，然后关闭窗口
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
import cv2

# 读取图像
img1=cv2.imread('./oxygen.jpg',16)

# 创建窗口，允许用户调整大小
cv2.namedWindow("imread", cv2.WINDOW_AUTOSIZE)

# 显示图像
cv2.imshow("imread", img1)

# 等待按键，然后关闭窗口
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import cv2 
 
# 打开视频文件
capture = cv2.VideoCapture("./dota2_testbug.mp4")  

if capture.isOpened():
  
  # 显示参数
  print("width: {}".format(capture.get(cv2.CAP_PROP_FRAME_WIDTH)))
  print("height: {}".ormat(capture.get(cv2.CAP_PROP_RAME_HEIGHT)))
  print("ps: {}".format(capture.get(cv2.CAP_PROP_FPS)))
  print("frame count: {}".format(capture.get(cv2.CAP_PROP_FRAME_COUNT))) 
else:
  print("Error: Could not open video file")
  
while (capture.isOpened()):
  
  # 视频文件被打开
  ret, frame = capture.read()     
  
  cv2.namedWindow("Video", cv2.WINDOW_KEEPRATIO)
  cv2.resizeWindow("Video", 700, 500)
  
  # 读取到视频文件
  if ret:   
    
    # 在窗口显示读取到的视频文件          
    cv2.imshow("Video", frame)     
  else:
    break
  
  key = cv2.waitKey(25)
  
  # 如果按键为ESC
  if key == 27:
    break
  
# 关闭视频文件  
capture.release()
cv2.waitKey(0)

cv2.destroyAllWindows()

width: 1920.0
height: 1080.0
fps: 28.44094680829375
frame count: 186.0
0.0


In [11]:
import cv2 
 
# 打开视频文件
capture = cv2.VideoCapture(0)  

if capture.isOpened():
  
  # 显示参数
  print("width: {}".format(capture.get(cv2.CAP_PROP_FRAME_WIDTH)))
  print("height: {}".format(capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
  print("fps: {}".format(capture.get(cv2.CAP_PROP_FPS)))
  print("frame count: {}".format(capture.get(cv2.CAP_PROP_FRAME_COUNT)))
else:
  print("Error: Could not open video file")
  
while (capture.isOpened()):
  
  # 视频文件被打开
  ret, frame = capture.read()     
  
  cv2.namedWindow("Video", cv2.WINDOW_KEEPRATIO)
  cv2.resizeWindow("Video", 700, 500)
  
  # 读取到视频文件
  if ret:   
    
    # 在窗口显示读取到的视频文件          
    cv2.imshow("Video", frame)     
  else:
    break
  
  key = cv2.waitKey(25)
  
  # 如果按键为ESC
  if key == 27:
    break
  
# 关闭视频文件  
capture.release()
cv2.waitKey(0)

cv2.destroyAllWindows()

width: 640.0
height: 480.0
fps: 30.0
frame count: -1.0
-1.0


In [6]:
import cv2
img = cv2.imread('./oxygen.jpg')

cv2.imwrite('./oxygen01.jpg', img)

cv2.imwrite("./oxygen02.jpg",img,[cv2.IMWRITE_JPEG_QUALITY,100])

cv2.imwrite("./oxygen03.jpg",img,[cv2.IMWRITE_JPEG_QUALITY,2])

cv2.imwrite("./oxygen04.jpg",img,[cv2.IMWRITE_JPEG_QUALITY,100,cv2.IMWRITE_JPEG_LUMA_QUALITY,10])

True

In [9]:
import cv2

# 图片序列文件夹
image_dir = './picture/'

# 图片数量
image_count = 21

# 尺寸
frame_size = (675, 981)

# videowriter
fourcc = cv2.VideoWriter.fourcc('I', '4', '2', '0')

# 生成视频时要注意帧率，因为是隔一帧采样，所以原本30帧的视频就要变为15帧
writer = cv2.VideoWriter('./picture.mp4', fourcc, 15, frame_size)

# 开始写入
for i in range(image_count):
  
  image = cv2.imread('{0}{1}.jpg'.format(image_dir, i))

  writer.write(image)
  
# 释放
writer.release()

# 提示消息
print('视频生成完成。')


视频生成完成。


In [10]:
import cv2
import numpy as np

fs = cv2.FileStorage('abc.yml', cv2.FileStorage_WRITE)
fs.write('mat1', np.random.uniform(0, 1, [2, 2]))
fs.write('mat2', np.random.randint(0, 10, [2, 2]))
fs.write('num1', 1)
fs.write('num2', 2.5)
fs.write('str1', 'abc')
fs.write('str2', '你好')
# 关闭文件
fs.release()

fs2 = cv2.FileStorage('abc.yml', cv2.FileStorage_READ)
mat1 = fs2.getNode('mat1').mat()
mat2 = fs2.getNode('mat2').mat()
num1 = fs2.getNode('num1').real()
num2 = fs2.getNode('num2').real()
str1 = fs2.getNode('str1').string()
str2 = fs2.getNode('str2').string()
# 关闭文件
fs2.release()

print(mat1)
print(mat2)
print(num1)
print(num2)
print(str1)
print(str2)



[[0.53575126 0.37671399]
 [0.56806879 0.52113629]]
[[9 8]
 [6 5]]
1.0
2.5
abc
你好


In [1]:
import cv2
src = cv2.imread('./oxygen.jpg')
dst1 = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
cv2.imwrite("./oxygen05.jpg", dst1)

True

In [2]:
dst2 = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
cv2.imwrite('./oxygen06.jpg', dst2)

True

In [3]:
dst3 = cv2.cvtColor(src, cv2.COLOR_BGR2RGB)
cv2.imwrite('./oxygen07.jpg', dst3)

True

In [4]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')
cv2.imshow('oxygen', bgr_image)

# 拆分通道
b, g, r = cv2.split(bgr_image) 

# 显示B通道图像
cv2.imshow('B', b) 

# 显示G通道图像
cv2.imshow('G', g)

# 显示R通道图像
cv2.imshow('R', r)

cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
import cv2

src = cv2.imread('./oxygen.jpg')

# 把BGR图像转换为HSV图像
scr2 =  cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

cv2.imshow('oxygen', scr2)

# 拆分通道
h ,s, v = cv2.split(scr2)

# 显示H通道图像
cv2.imshow('H', b) 

# 显示S通道图像
cv2.imshow('S', s)

# 显示V通道图像
cv2.imshow('V', v)

cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')

# 拆分通道
b, g, r = cv2.split(bgr_image) 

# 按B→G→R的顺序合并通道
bgr = cv2.merge([b, g, r])

cv2.imshow("BGR", bgr)

cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')

# 从BGR色彩空间转换到HSV色彩空间
hsv_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2HSV)

# 拆分HSV图像中的通道
h, s, v = cv2.split(hsv_image) 

# 合并拆分后的通道图像
hsv = cv2.merge([h, s, v]) 

# 合并通道后的图像从HSV色彩空间转换到BGR色彩空间
bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

# 显示BGR图像
cv2.imshow("BGR", bgr) 

cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')
cv2.imshow("oxygen", bgr_image)

# 从BGR色彩空间转换到HSV色彩空间
hsv_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2HSV)

# 拆分HSV图像中的通道
h, s, v = cv2.split(hsv_image) 

# 将H通道的值调整为180
h[:, :] = 180 

# 合并拆分后的通道图像
hsv = cv2.merge([h, s, v]) 


# 合并通道后的图像从HSV色彩空间转换到BGR色彩空间
new_Image = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
cv2.imshow("NEW",new_Image)

cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')

# 从BGR色彩空间转换到BGRA色彩空间
bgra_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2BGRA)

# 显示BGRA图像
cv2.imshow('BGRA', bgr_image)

# 拆分BGRA图像中的通道
b, g, r, a = cv2.split(bgra_image) 

# 将BGRA图像的透明度调整为172（半透明）
a[:, :] = 172 

# 合并拆分后并将透明度调整为172的通道图像
bgra_172 = cv2.merge([b, g, r, a]) 

# 将BG图像的透明度调整为0（透明）
a[:, :] = 0 

# 合并拆分后并将透明度调整为0的通道图像
bgra_0 = cv2.merge([b, g, r, a]) 

cv2.imwrite('./oxygen_bgra.jpg',bgra_image)
cv2.imwrite('./oxygen_bgra172.jpg',bgra_172)
cv2.imwrite('./oxygen_bgra0.jpg',bgra_0)

# 显示透明度为172的BGRA图像
cv2.imshow('A = 172', bgra_172)

# 显示透明度为0的BGRA图像
cv2.imshow('A = 0', bgra_0)
 
cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
import cv2 as cv
import numpy as np

# 新建矩阵array
array = np.array([1, 2, 3, 4, 5, 10, 6, 7, 8, 9, 10, 0])

# 将array调整为3*4的单通道图像
img1 = array.reshape((3, 4))

print(img1)

minval_1, maxval_1, minloc_1, maxloc_1 = cv.minMaxLoc(img1)

temp1 = img1[2, 1]
temp2 = img1[1, 2]

print('图像img1中最小值为：{}, 其位置为：{}' .format(minval_1, minloc_1))
print('图像img1中最大值为：{}, 其位置为：{}' .format(maxval_1, maxloc_1))


[[ 1  2  3  4]
 [ 5 10  6  7]
 [ 8  9 10  0]]
图像img1中最小值为：0.0, 其位置为：(3, 2)
图像img1中最大值为：10.0, 其位置为：(1, 1)


In [26]:
import numpy as np

# 新建矩阵A1
A1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(A1)
print('----------')

# 将A1调整为3*4的单通道图像(矩阵)
img1 = A1.reshape((3, 4))

print(img1)
print('----------')

# 将A1调整为 2*2*3的两通道图像(矩阵)
img2 = A1.reshape((2, 2, 3))

print(img2)
print('----------')

# 将某一维度的值设为-1，函数自动计算出其值
img3 = A1.reshape((2, 2, -1))

print(img3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
----------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
import cv2
import numpy as np
 
# 新建矩阵array
array = np.array([1, 2, 3, 4, 5, 10, 6, 7, 8, 9, 10, 0])

# 将array调整为3*4的单通道图像img1
img1 = array.reshape((3, 4))

# 将array调整为3*2*2的多通道图像img2
img2 = array.reshape((3, 2, 2))
 
# 计算img1的均值
mean_img1 = cv2.mean(img1)

# 计算img2的均值
mean_img2 = cv2.mean(img2)

# 计算img1的均值和标准差
mean_std_dev_img1 = cv2.meanStdDev(img1)

# 计算img2的均值和标准差
mean_std_dev_img2 = cv2.meanStdDev(img2)
 
print('mean函数计算结果如下：{}')
print('图像img1的均值为：{}'.format(mean_img1))
print('图像img2的均值为：{}'.format(mean_img2))
print('第一个通道的均值为：{}'.format(mean_img2[0]))
print('第二个通道的均值为：{}'.format(mean_img2[1]))
      
print('----------')
print('meanStdDev函数计算结果如下：')
print('图像img1的均值为：{}'.format(mean_img1[0]))
print('标准差为：{}'.format(mean_std_dev_img1[1]))
print('图像img2的均值为：{}'.format(mean_img2))
print('第一个通道的均值为：{}'.format(mean_img2[0]))

print('第二个通道的均值为：{}'.format(mean_img2[1]))
print('均值为：{}'.format(mean_std_dev_img2[0]))
print('标准差为：{}'.format(mean_std_dev_img2[1]))
print('第一个通道的标准差为：{}'.format(float(mean_std_dev_img2[1][0])))
print('第二个通道的标准差为：{}'.format(float(mean_std_dev_img2[1][0])))

mean函数计算结果如下：{}
图像img1的均值为：(5.416666666666666, 0.0, 0.0, 0.0)
图像img2的均值为：(5.5, 5.333333333333333, 0.0, 0.0)
第一个通道的均值为：5.5
第二个通道的均值为：5.333333333333333
----------
meanStdDev函数计算结果如下：
图像img1的均值为：5.416666666666666
标准差为：[[3.32812092]]
图像img2的均值为：(5.5, 5.333333333333333, 0.0, 0.0)
第一个通道的均值为：5.5
第二个通道的均值为：5.333333333333333
均值为：[[5.5       ]
 [5.33333333]]
标准差为：[[2.98607881]
 [3.63623737]]
第一个通道的标准差为：2.9860788111948193
第二个通道的标准差为：2.9860788111948193


In [36]:
import numpy as np
import cv2 as cv

A1 = np.array(
  [
    [1, 1, 1],
    [66, 66, 66],
    [55, 55, 55]
  ], dtype='int8'
)

B1 = np.array(
  [
    [88, 88, 88],
    [2, 2, 2],
    [55, 55, 55]
  ], dtype='int8'
)

C1 = cv.max(A1, B1)
C2 = cv.min(A1, B1)

print(C1)
print('----------')
print(C2)

[[88 88 88]
 [66 66 66]
 [55 55 55]]
----------
[[ 1  1  1]
 [ 2  2  2]
 [55 55 55]]


In [3]:
import cv2
import numpy as np

A1 = np.array(
  [
    [1, 1, 1],
    [66, 66, 66],
    [55, 55, 55]
  ], dtype='uint8'
)
 
B1 = np.array(
  [
    [88, 88, 88],
    [2, 2, 2],
    [55, 55, 55]
  ], dtype='uint8'
)

C1 = cv2.bitwise_and(A1, B1)
print(C1)
print('----------')
C2 = cv2.bitwise_or(A1, B1)
print(C2)
print('----------')
C3 = cv2.bitwise_not(A1)
print(C3)
print('----------')
C4 = cv2.bitwise_xor(A1, B1)
print(C4)

[[ 0  0  0]
 [ 2  2  2]
 [55 55 55]]
----------
[[89 89 89]
 [66 66 66]
 [55 55 55]]
----------
[[254 254 254]
 [189 189 189]
 [200 200 200]]
----------
[[89 89 89]
 [64 64 64]
 [ 0  0  0]]


In [2]:
import cv2
src = cv2.imread('./oxygen.jpg')
thresh, result0 = cv2.threshold(src, 80, 255, cv2.THRESH_BINARY)
cv2.imshow('result0', result0)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
import cv2

src = cv2.imread('./oxygen.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
thresh, result1 = cv2.threshold(gray, 80, 255, cv2.THRESH_BINARY)
cv2.imshow('result1', result1)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import cv2

src = cv2.imread('./oxygen.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
thresh, result2 = cv2.threshold(gray, 80, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('result2', result2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
import cv2

src = cv2.imread('./oxygen.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
thresh, result3 = cv2.threshold(gray, 80, 255, cv2.THRESH_TOZERO)
cv2.imshow('result3', result3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import cv2

src = cv2.imread('./oxygen.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
thresh, result4 = cv2.threshold(gray, 80, 255, cv2.THRESH_TOZERO_INV)
cv2.imshow('result4', result4)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import cv2

src = cv2.imread('./oxygen.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
thresh, result5 = cv2.threshold(gray, 80, 255, cv2.THRESH_TRUNC)
cv2.imshow('result5', result5)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import cv2
 
img = cv2.imread('./oxygen.jpg') 
img_gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

thresh,img_bin = cv2.threshold(img_gray,10, 255, cv2.THRESH_BINARY|cv2.THRESH_OTSU)
cv2.imshow('threshold',img_bin)
img_ret11 = cv2.adaptiveThreshold(img_gray,  255, cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,55,0 ) 
cv2.imshow('adaptiveThreshold',img_ret11)
img_ret12 = cv2.adaptiveThreshold(img_gray,  255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,55,0 )

cv2.imshow('adaptive2',img_ret12)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
import cv2
import numpy as np


A1 = np.array(
  [
    [40, 40, 40],
    [110, 110, 110],
    [240, 240, 240]
  ], dtype='uint8'
)

print(A1)
print('----------')

LUT_1 = np.zeros(256, dtype='uint8')
LUT_1[0: 100] = 50
LUT_1[100: 200] = 70
LUT_1[200:] = 80

B1 = cv2.LUT(A1, LUT_1)

print(B1)

[[ 40  40  40]
 [110 110 110]
 [240 240 240]]
----------
[[50 50 50]
 [70 70 70]
 [80 80 80]]


In [17]:
import cv2

src1 = cv2.imread('./oxygen.jpg')
scr2 = cv2.imread('./oxygen06.jpg')

src1 = cv2.resize(src1, dsize=(500, 500))
scr2 = cv2.resize(scr2, dsize=(500, 500))

# 水平拼接图像
hconcat_img = cv2.hconcat([src1, scr2])

# 垂直拼接图像
vconcat_img = cv2.vconcat([src1, scr2])

cv2.imshow('hconcat_img', hconcat_img)
cv2.imshow('vconcat_img', vconcat_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
import cv2

img = cv2.imread('./oxygen.jpg')

# cv2.imshow('img_src', img)

# 将图像缩小（利用参数dsize设定输出图像的大小）
small_img = cv2.resize(img, (150, 100), fx=0, fy=0, interpolation=cv2.INTER_AREA)
cv2.imshow('small_img', small_img)

# 最近邻插值（利用参数fx和fy设定输出图像的缩放比例）
big_img1 = cv2.resize(small_img, (0, 0), fx=2, fy=2, interpolation=cv2.INTER_NEAREST)
cv2.imshow('big_img1', big_img1)

# 双线性插值（利用参数dsize设定输出图像的大小）
big_img2 = cv2.resize(small_img, (300, 200), fx=0, fy=0, interpolation=cv2.INTER_LINEAR)
cv2.imshow('big_img2', big_img2)

# 双三次插值（利用参数fx和fy设定输出图像的缩放比例）
big_img3 = cv2.resize(small_img, (0, 0), fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
cv2.imshow('big_img3', big_img3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
import cv2

img = cv2.imread("./oxygen.jpg")
cv2.imshow("oxygen", img)

# 水平翻转
horizontally_img = cv2.flip(img, 0)
cv2.imshow("horizontally_img", horizontally_img)

# 垂直翻转
vertically_img = cv2.flip(img, 1)
cv2.imshow("vertically_img", vertically_img)

# 对角线翻转
horizontally_vertically_img = cv2.flip(img, -1)
cv2.imshow("horizontally_vertically_img", horizontally_vertically_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

img = cv2.imread('./oxygen.jpg')

print(img.shape)

# 设置图像旋转角度、尺寸、旋转中心参数
angle = 30
h, w = img.shape[0:2]  # 这句话也可用三帽号规则的高级写法写成 h, w = img.shape[:-1]，相当于用索引-1代替索引2，注意左闭右开规则。
size = (w, h)
center = (w / 2.0, h / 2.0)

# 计算仿射变换矩阵
rotation0 = cv2.getRotationMatrix2D(center, angle, 1)

# 进行仿射变换
img_warp0 = cv2.warpAffine(img, rotation0, size)

# 根据定义的三个点进行仿射变换
src_points = np.array([[0, 0], [0, h - 1], [w - 1, h - 1]], dtype='float32')
dst_points = np.array([[w * 0.11, h * 0.2], [w * 0.15, h * 0.7], [w * 0.81, h * 0.85]], dtype='float32')

rotation1 = cv2.getAffineTransform(src_points, dst_points)
img_warp1 = cv2.warpAffine(img, rotation1, size)

# 展示结果
cv2.imshow('img_src', img)
cv2.imshow('img_warp0', img_warp0)
cv2.imshow('img_warp1', img_warp1)

cv2.waitKey(0)
cv2.destroyAllWindows()

(1080, 1728, 3)


In [3]:
import cv2
import numpy as np

img = cv2.imread('./oxygen.jpg')

h, w = img.shape[:-1]
size = (w, h)

# 透视变换前的四个角点坐标
src_points = np.array([[65, 70], [198, 67], [50, 164], [205, 163]], dtype='float32')

# 设置透视变换后四个角点坐标
max_pt = np.max(src_points)
dst_points = np.array([[50, 50], [180, 50], [50, 180], [180, 180]], dtype='float32')

# 计算透视变换矩阵
rotation = cv2.getPerspectiveTransform(src_points, dst_points)

# 透视变换投影
img_warp = cv2.warpPerspective(img, rotation, size)

# 展示结果
cv2.imshow('src_img', img)
cv2.imshow('perspective_img', img_warp)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
import numpy as np
import cv2 
 
Src_size = 101
Dst_size = Src_size
 
A = np.zeros((Src_size, Src_size), dtype='uint8')
 
cv2.circle(A, (Src_size//2, Src_size//2), Src_size//2, 255, 1)
 
cv2.imshow('A', A)
 
C = cv2.warpPolar(A, (Dst_size, 360), (Src_size//2, Src_size//2), Src_size//2, cv2.INTER_LINEAR + cv2.WARP_POLAR_LINEAR)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import numpy as np
import cv2
 
img_src = cv2.imread('./circle.jpg')

cv2.imshow('img_src', img_src)

img_polar = cv2.warpPolar(img_src, (338, 360), (338//2, 338//2), 338//2, cv2.INTER_LINEAR + cv2.WARP_POLAR_LINEAR)
cv2.imshow('img_polar', img_polar)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
import cv2
import numpy as np

#创建黑色图像
img = np.zeros((256,256,3), dtype = 'uint8')

#绘制圆形
cv2.circle(img, (100,100), 50, (255,255,0), 4)

#显示图像
cv2.imshow("circle", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
#创建黑色图像
img = np.zeros((256,256,3), dtype = 'uint8')

#绘制直线
cv2.line(img, (0,0), (255,255), (55,255,155), 5)

#显示图像
cv2.imshow("line", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
#创建黑色图像
img = np.zeros((256,256,3), dtype = 'uint8')

#绘制椭圆
#椭圆中心(120,100) 长轴和短轴为(100,50)
#偏转角度为20
#圆弧起始角的角度0 圆弧终结角的角度360
#颜色(255,0,255) 线条粗细2
cv2.ellipse(img, (120, 100), (100, 50), 20, 0, 360, (255, 0, 255), 2)

#显示图像
cv2.imshow("ellipse", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
import cv2
import numpy as np

img = np.zeros((400, 400, 3), dtype = 'uint8')

# points = cv2.ellipse2Poly((200, 200), (100, 70), 0, 0, 360, 3)  # 参数delta=3
points = cv2.ellipse2Poly((200, 200), (100, 70), 0, 0, 360, 30)  # 参数delta=30

for i in range(len(points) - 1):
  img = cv2.line(img, (points[i][0], points[i][1]), (points[i + 1][0], points[i + 1][1]),(255, 0, 0), 2, cv2.LINE_4, 0)

cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
import cv2
import numpy as np

#创建黑色图像
img = np.zeros((256,256,3), dtype = 'uint8')

#绘制矩形
cv2.rectangle(img, (20,20), (150,250), (255,0,0), 2)

#显示图像
cv2.imshow("rectangle", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img = np.zeros((1080, 1920, 3), dtype = 'uint8')
area1 = np.array([[250, 200], [300, 100], [750, 800], [100, 1000]])
 
cv2.fillPoly(img, [area1], (255, 255, 255))
 
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
import cv2
import numpy as np

#创建黑色图像
img = np.zeros((256,256,3), dtype = 'uint8')

#绘制文字
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img, 'SSSSssZZzZZzzLLllLLlL',(10, 100), font, 0.5, (255, 255, 0), 2)

#显示图像
cv2.imshow("polylines", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
import numpy as np

A1 = np.zeros((7, 7), dtype = 'uint8')

print(A1)
print('----------')

# 通过“=”和索引实现ROI区域的浅拷贝
B2 = A1[0:4, 0:3]
B2[1, 1] = 1

print(B2)
print('----------')

print(A1)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----------
[[0 0 0]
 [0 1 0]
 [0 0 0]
 [0 0 0]]
----------
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [45]:
import numpy as np

A1 = np.zeros((7, 7), dtype = 'uint8')

print('A1:')
print(A1)
print('----------')

# 通过“=”和索引实现ROI区域的浅拷贝
B1 = A1[0:4, 0:3]

print('B1:')
print(B1)
print('----------')

# 通过函数copy()实现ROI区域的深拷贝
C1 = B1.copy()

C1[1, 1] = 1

print('C1:')
print(C1)


A1:
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----------
B1:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
----------
C1:
[[0 0 0]
 [0 1 0]
 [0 0 0]
 [0 0 0]]


In [46]:
import numpy as np

A1 = np.zeros((7, 7), dtype = 'uint8')
B1 = np.ones((3, 3), dtype = 'uint8')

A1[1:4, 1:4] = B1

B1[1, 1] = 0

print('A1:')
print(A1)
print('----------')

print('B1:')
print(B1)

A1:
[[0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 1 1 1 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----------
B1:
[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [47]:
import cv2 
 
src = cv2.imread('./oxygen.jpg')

# 第0层高斯金字塔实际上就是原图像
G_0 = src  
print('第0层高斯金字塔图像的尺寸：{}'.format(src.shape[:2]))
cv2.imshow("G_0", src)
 
# 生成第1层高斯金字塔G_1
G_1 = cv2.pyrDown(G_0)
print('第1层高斯金字塔图像的尺寸：{}'.format(G_1.shape[:2]))
cv2.imshow("G_1 ", G_1)
 
# 为了计算第0层拉普拉斯金字塔，我们需要先计算出Pyrup(G_1)
Pyrup_G_1 = cv2.pyrUp(G_1)
print('第1层高斯金字塔进行上采样+高斯卷积模糊滤波后的尺寸：{}'.format(Pyrup_G_1.shape[:2]))
cv2.imshow("Pyrup_G_1", Pyrup_G_1)
 
# 计算第0层拉普拉斯金字塔图像，L_0=G_0-Pyrup(Pyrdown(G_0))
L_0 = cv2.subtract(G_0, Pyrup_G_1, dst = None, mask = None, dtype = cv2.CV_16S)
print('第0层拉普拉斯金字塔的尺寸：{}'.format(L_0.shape[:2]))
 
# 以下几行代码是显示出第0层拉普拉斯金字塔的图像
L_0_norm = L_0
cv2.normalize(L_0, L_0_norm, 0, 255, cv2.NORM_MINMAX)
L_0_norm = L_0_norm.astype('uint8')
L_0_norm_gray = cv2.cvtColor(L_0_norm, cv2.COLOR_BGR2GRAY)
cv2.imshow("L_0_norm_gray", L_0_norm_gray)
 
# 利用第1层高斯金字塔图像和第0层拉普拉斯金字塔图像重构第0层高斯金字塔
# 第0层高斯金字塔实际上就是原图
G_0_reconstruction = cv2.add(Pyrup_G_1, L_0, dst = None, mask = None, dtype = cv2.CV_16S)
cv2.normalize(G_0_reconstruction, G_0_reconstruction, 0, 255, cv2.NORM_MINMAX)
G_0_reconstruction = G_0_reconstruction.astype('uint8')
print('重构的第0层高斯金字塔图像的尺寸：{}'.format(G_0_reconstruction.shape[:2]))
cv2.imshow("G_0_reconstruction", G_0_reconstruction)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

第0层高斯金字塔图像的尺寸：(1080, 1728)
第1层高斯金字塔图像的尺寸：(540, 864)
第1层高斯金字塔进行上采样+高斯卷积模糊滤波后的尺寸：(1080, 1728)
第0层拉普拉斯金字塔的尺寸：(1080, 1728)
重构的第0层高斯金字塔图像的尺寸：(1080, 1728)


In [53]:
import cv2 
import numpy as np
 
 
def on_change_trackbar(x):
  global A1_copy, value

  A1_copy[:, :] = 0
  value = cv2.getTrackbarPos('pos', 'dyn_gray_value')
  A1_copy = A1_copy + value

  cv2.imshow("dyn_gray_value", A1_copy)

 
A1 =  np.zeros((200, 300), dtype = 'uint8')
cv2.namedWindow('dyn_gray_value')
cv2.imshow("dyn_gray_value", A1)
 
value = 20
 
A1_copy = A1.copy()
 
cv2.createTrackbar('pos', 'dyn_gray_value', value, 255, on_change_trackbar)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [59]:
import cv2

def draw(event, x, y, flags, param):
    global img, pre_pts
 
    # 鼠标右键按下
    if event == cv2.EVENT_RBUTTONDOWN:
        print('请点击鼠标左键进行轨迹的绘制。')
 
    # 鼠标左键按下
    if event == cv2.EVENT_LBUTTONDOWN:
        pre_pts = (x, y)
        print('轨迹起始坐标为：{}, {}'.format(x, y))
 
    # 鼠标移动
    if event == cv2.EVENT_MOUSEMOVE and flags == cv2.EVENT_FLAG_LBUTTON:
        pts = (x, y)
        img = cv2.line(img, pre_pts, pts, (0, 0, 255), 2, 5,0)
        pre_pts = pts
        cv2.imshow('image', img)

# 读取图像并判断是否读取成功
img = cv2.imread('./oxygen.jpg')
img1 = img.copy()

pre_pts = 0, 0
cv2.imshow('image', img)
cv2.setMouseCallback('image', draw)

cv2.waitKey(0)
cv2.destroyAllWindows()

轨迹起始坐标为：835, 702
