In [6]:
import os
import cv2
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from IPython.display import Image

In [7]:
import cv2
img1=cv2.imread('./oxygen.jpg',2|4)
cv2.namedWindow("imread", cv2.WINDOW_NORMAL)
cv2.imshow("imread", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import cv2
img1=cv2.imread('./oxygen.jpg', 0)
cv2.namedWindow("imread")
cv2.imshow("imread", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import cv2

# 读取图像
img1=cv2.imread('./oxygen.jpg',2|4)

# 创建窗口，允许用户调整大小
cv2.namedWindow("imread", cv2.WINDOW_AUTOSIZE)

# 显示图像
cv2.imshow("imread", img1)

# 等待按键，然后关闭窗口
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
import cv2

# 读取图像
img1=cv2.imread('./oxygen.jpg',16)

# 创建窗口，允许用户调整大小
cv2.namedWindow("imread", cv2.WINDOW_AUTOSIZE)

# 显示图像
cv2.imshow("imread", img1)

# 等待按键，然后关闭窗口
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import cv2 
 
# 打开视频文件
capture = cv2.VideoCapture("./dota2_testbug.mp4")  

if capture.isOpened():
  
  # 显示参数
  print("width: {}".format(capture.get(cv2.CAP_PROP_FRAME_WIDTH)))
  print("height: {}".ormat(capture.get(cv2.CAP_PROP_RAME_HEIGHT)))
  print("ps: {}".format(capture.get(cv2.CAP_PROP_FPS)))
  print("frame count: {}".format(capture.get(cv2.CAP_PROP_FRAME_COUNT))) 
else:
  print("Error: Could not open video file")
  
while (capture.isOpened()):
  
  # 视频文件被打开
  ret, frame = capture.read()     
  
  cv2.namedWindow("Video", cv2.WINDOW_KEEPRATIO)
  cv2.resizeWindow("Video", 700, 500)
  
  # 读取到视频文件
  if ret:   
    
    # 在窗口显示读取到的视频文件          
    cv2.imshow("Video", frame)     
  else:
    break
  
  key = cv2.waitKey(25)
  
  # 如果按键为ESC
  if key == 27:
    break
  
# 关闭视频文件  
capture.release()
cv2.waitKey(0)

cv2.destroyAllWindows()

width: 1920.0
height: 1080.0
fps: 28.44094680829375
frame count: 186.0
0.0


In [11]:
import cv2 
 
# 打开视频文件
capture = cv2.VideoCapture(0)  

if capture.isOpened():
  
  # 显示参数
  print("width: {}".format(capture.get(cv2.CAP_PROP_FRAME_WIDTH)))
  print("height: {}".format(capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
  print("fps: {}".format(capture.get(cv2.CAP_PROP_FPS)))
  print("frame count: {}".format(capture.get(cv2.CAP_PROP_FRAME_COUNT)))
else:
  print("Error: Could not open video file")
  
while (capture.isOpened()):
  
  # 视频文件被打开
  ret, frame = capture.read()     
  
  cv2.namedWindow("Video", cv2.WINDOW_KEEPRATIO)
  cv2.resizeWindow("Video", 700, 500)
  
  # 读取到视频文件
  if ret:   
    
    # 在窗口显示读取到的视频文件          
    cv2.imshow("Video", frame)     
  else:
    break
  
  key = cv2.waitKey(25)
  
  # 如果按键为ESC
  if key == 27:
    break
  
# 关闭视频文件  
capture.release()
cv2.waitKey(0)

cv2.destroyAllWindows()

width: 640.0
height: 480.0
fps: 30.0
frame count: -1.0
-1.0


In [6]:
import cv2
img = cv2.imread('./oxygen.jpg')

cv2.imwrite('./oxygen01.jpg', img)

cv2.imwrite("./oxygen02.jpg",img,[cv2.IMWRITE_JPEG_QUALITY,100])

cv2.imwrite("./oxygen03.jpg",img,[cv2.IMWRITE_JPEG_QUALITY,2])

cv2.imwrite("./oxygen04.jpg",img,[cv2.IMWRITE_JPEG_QUALITY,100,cv2.IMWRITE_JPEG_LUMA_QUALITY,10])

True

In [9]:
import cv2

# 图片序列文件夹
image_dir = './picture/'

# 图片数量
image_count = 21

# 尺寸
frame_size = (675, 981)

# videowriter
fourcc = cv2.VideoWriter.fourcc('I', '4', '2', '0')

# 生成视频时要注意帧率，因为是隔一帧采样，所以原本30帧的视频就要变为15帧
writer = cv2.VideoWriter('./picture.mp4', fourcc, 15, frame_size)

# 开始写入
for i in range(image_count):
  
  image = cv2.imread('{0}{1}.jpg'.format(image_dir, i))

  writer.write(image)
  
# 释放
writer.release()

# 提示消息
print('视频生成完成。')


视频生成完成。


In [10]:
import cv2
import numpy as np

fs = cv2.FileStorage('abc.yml', cv2.FileStorage_WRITE)
fs.write('mat1', np.random.uniform(0, 1, [2, 2]))
fs.write('mat2', np.random.randint(0, 10, [2, 2]))
fs.write('num1', 1)
fs.write('num2', 2.5)
fs.write('str1', 'abc')
fs.write('str2', '你好')
# 关闭文件
fs.release()

fs2 = cv2.FileStorage('abc.yml', cv2.FileStorage_READ)
mat1 = fs2.getNode('mat1').mat()
mat2 = fs2.getNode('mat2').mat()
num1 = fs2.getNode('num1').real()
num2 = fs2.getNode('num2').real()
str1 = fs2.getNode('str1').string()
str2 = fs2.getNode('str2').string()
# 关闭文件
fs2.release()

print(mat1)
print(mat2)
print(num1)
print(num2)
print(str1)
print(str2)



[[0.53575126 0.37671399]
 [0.56806879 0.52113629]]
[[9 8]
 [6 5]]
1.0
2.5
abc
你好


In [1]:
import cv2
src = cv2.imread('./oxygen.jpg')
dst1 = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
cv2.imwrite("./oxygen05.jpg", dst1)

True

In [2]:
dst2 = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
cv2.imwrite('./oxygen06.jpg', dst2)

True

In [3]:
dst3 = cv2.cvtColor(src, cv2.COLOR_BGR2RGB)
cv2.imwrite('./oxygen07.jpg', dst3)

True

In [4]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')
cv2.imshow('oxygen', bgr_image)

# 拆分通道
b, g, r = cv2.split(bgr_image) 

# 显示B通道图像
cv2.imshow('B', b) 

# 显示G通道图像
cv2.imshow('G', g)

# 显示R通道图像
cv2.imshow('R', r)

cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
import cv2

src = cv2.imread('./oxygen.jpg')

# 把BGR图像转换为HSV图像
scr2 =  cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

cv2.imshow('oxygen', scr2)

# 拆分通道
h ,s, v = cv2.split(scr2)

# 显示H通道图像
cv2.imshow('H', b) 

# 显示S通道图像
cv2.imshow('S', s)

# 显示V通道图像
cv2.imshow('V', v)

cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')

# 拆分通道
b, g, r = cv2.split(bgr_image) 

# 按B→G→R的顺序合并通道
bgr = cv2.merge([b, g, r])

cv2.imshow("BGR", bgr)

cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')

# 从BGR色彩空间转换到HSV色彩空间
hsv_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2HSV)

# 拆分HSV图像中的通道
h, s, v = cv2.split(hsv_image) 

# 合并拆分后的通道图像
hsv = cv2.merge([h, s, v]) 

# 合并通道后的图像从HSV色彩空间转换到BGR色彩空间
bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

# 显示BGR图像
cv2.imshow("BGR", bgr) 

cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')
cv2.imshow("oxygen", bgr_image)

# 从BGR色彩空间转换到HSV色彩空间
hsv_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2HSV)

# 拆分HSV图像中的通道
h, s, v = cv2.split(hsv_image) 

# 将H通道的值调整为180
h[:, :] = 180 

# 合并拆分后的通道图像
hsv = cv2.merge([h, s, v]) 


# 合并通道后的图像从HSV色彩空间转换到BGR色彩空间
new_Image = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
cv2.imshow("NEW",new_Image)

cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
import cv2
 
bgr_image = cv2.imread('./oxygen.jpg')

# 从BGR色彩空间转换到BGRA色彩空间
bgra_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2BGRA)

# 显示BGRA图像
cv2.imshow('BGRA', bgr_image)

# 拆分BGRA图像中的通道
b, g, r, a = cv2.split(bgra_image) 

# 将BGRA图像的透明度调整为172（半透明）
a[:, :] = 172 

# 合并拆分后并将透明度调整为172的通道图像
bgra_172 = cv2.merge([b, g, r, a]) 

# 将BG图像的透明度调整为0（透明）
a[:, :] = 0 

# 合并拆分后并将透明度调整为0的通道图像
bgra_0 = cv2.merge([b, g, r, a]) 

cv2.imwrite('./oxygen_bgra.jpg',bgra_image)
cv2.imwrite('./oxygen_bgra172.jpg',bgra_172)
cv2.imwrite('./oxygen_bgra0.jpg',bgra_0)

# 显示透明度为172的BGRA图像
cv2.imshow('A = 172', bgra_172)

# 显示透明度为0的BGRA图像
cv2.imshow('A = 0', bgra_0)
 
cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
import cv2 as cv
import numpy as np

# 新建矩阵array
array = np.array([1, 2, 3, 4, 5, 10, 6, 7, 8, 9, 10, 0])

# 将array调整为3*4的单通道图像
img1 = array.reshape((3, 4))

print(img1)

minval_1, maxval_1, minloc_1, maxloc_1 = cv.minMaxLoc(img1)

temp1 = img1[2, 1]
temp2 = img1[1, 2]

print('图像img1中最小值为：{}, 其位置为：{}' .format(minval_1, minloc_1))
print('图像img1中最大值为：{}, 其位置为：{}' .format(maxval_1, maxloc_1))


[[ 1  2  3  4]
 [ 5 10  6  7]
 [ 8  9 10  0]]
图像img1中最小值为：0.0, 其位置为：(3, 2)
图像img1中最大值为：10.0, 其位置为：(1, 1)


In [26]:
import numpy as np

# 新建矩阵A1
A1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(A1)
print('----------')

# 将A1调整为3*4的单通道图像(矩阵)
img1 = A1.reshape((3, 4))

print(img1)
print('----------')

# 将A1调整为 2*2*3的两通道图像(矩阵)
img2 = A1.reshape((2, 2, 3))

print(img2)
print('----------')

# 将某一维度的值设为-1，函数自动计算出其值
img3 = A1.reshape((2, 2, -1))

print(img3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
----------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
import cv2
import numpy as np
 
# 新建矩阵array
array = np.array([1, 2, 3, 4, 5, 10, 6, 7, 8, 9, 10, 0])

# 将array调整为3*4的单通道图像img1
img1 = array.reshape((3, 4))

# 将array调整为3*2*2的多通道图像img2
img2 = array.reshape((3, 2, 2))
 
# 计算img1的均值
mean_img1 = cv2.mean(img1)

# 计算img2的均值
mean_img2 = cv2.mean(img2)

# 计算img1的均值和标准差
mean_std_dev_img1 = cv2.meanStdDev(img1)

# 计算img2的均值和标准差
mean_std_dev_img2 = cv2.meanStdDev(img2)
 
print('mean函数计算结果如下：{}')
print('图像img1的均值为：{}'.format(mean_img1))
print('图像img2的均值为：{}'.format(mean_img2))
print('第一个通道的均值为：{}'.format(mean_img2[0]))
print('第二个通道的均值为：{}'.format(mean_img2[1]))
      
print('----------')
print('meanStdDev函数计算结果如下：')
print('图像img1的均值为：{}'.format(mean_img1[0]))
print('标准差为：{}'.format(mean_std_dev_img1[1]))
print('图像img2的均值为：{}'.format(mean_img2))
print('第一个通道的均值为：{}'.format(mean_img2[0]))

print('第二个通道的均值为：{}'.format(mean_img2[1]))
print('均值为：{}'.format(mean_std_dev_img2[0]))
print('标准差为：{}'.format(mean_std_dev_img2[1]))
print('第一个通道的标准差为：{}'.format(float(mean_std_dev_img2[1][0])))
print('第二个通道的标准差为：{}'.format(float(mean_std_dev_img2[1][0])))

mean函数计算结果如下：{}
图像img1的均值为：(5.416666666666666, 0.0, 0.0, 0.0)
图像img2的均值为：(5.5, 5.333333333333333, 0.0, 0.0)
第一个通道的均值为：5.5
第二个通道的均值为：5.333333333333333
----------
meanStdDev函数计算结果如下：
图像img1的均值为：5.416666666666666
标准差为：[[3.32812092]]
图像img2的均值为：(5.5, 5.333333333333333, 0.0, 0.0)
第一个通道的均值为：5.5
第二个通道的均值为：5.333333333333333
均值为：[[5.5       ]
 [5.33333333]]
标准差为：[[2.98607881]
 [3.63623737]]
第一个通道的标准差为：2.9860788111948193
第二个通道的标准差为：2.9860788111948193


In [36]:
import numpy as np
import cv2 as cv

A1 = np.array(
  [
    [1, 1, 1],
    [66, 66, 66],
    [55, 55, 55]
  ], dtype='int8'
)

B1 = np.array(
  [
    [88, 88, 88],
    [2, 2, 2],
    [55, 55, 55]
  ], dtype='int8'
)

C1 = cv.max(A1, B1)
C2 = cv.min(A1, B1)

print(C1)
print('----------')
print(C2)

[[88 88 88]
 [66 66 66]
 [55 55 55]]
----------
[[ 1  1  1]
 [ 2  2  2]
 [55 55 55]]
