In [1]:
# 导包
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell # 这个对象设置所有行全部输出

# 导入鸢尾花数据集
from sklearn.datasets import load_iris

# 导入数据集划分工具
from sklearn.model_selection import train_test_split

# 导入逻辑回归模型
from sklearn.linear_model import LogisticRegression

# 导入分类模型评估指标accuracy_score
from sklearn.metrics import accuracy_score

# 设置该对象ast_node_interactivity属性的值为all，表示在notebook下每一行有输出的代码全部输出运算结果
InteractiveShell.ast_node_interactivity = "all"

# 解决坐标轴刻度负号乱码
plt.rcParams['axes.unicode_minus'] = False

# 解决中文乱码问题
plt.rcParams['font.sans-serif'] = ['Simhei']
plt.style.use('ggplot')

In [3]:
dataset  = load_iris()
x = dataset.data
y = dataset.target

In [4]:
# 数据集划分
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x, y, test_size=0.3, random_state=123)

In [5]:
# 构建逻辑回归模型
clf = LogisticRegression()

# 训练模型
clf = clf.fit(Xtrain, Ytrain)

# 模型前向计算（预测）
y_pred = clf.predict(Xtest)
y_pred

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2])

In [7]:
# 评估模型准确率
accuracy_score(y_pred, Ytest)

0.9333333333333333

In [8]:
# 获取预测结果的概率分布
clf.predict_proba(Xtest)

array([[1.19011338e-03, 6.34446769e-01, 3.64363117e-01],
       [5.10454735e-05, 1.03746097e-01, 8.96202858e-01],
       [2.24501654e-05, 4.80883518e-02, 9.51889198e-01],
       [3.25714656e-02, 9.22526829e-01, 4.49017055e-02],
       [9.80280348e-01, 1.97196168e-02, 3.48110036e-08],
       [2.55351465e-03, 5.13729444e-01, 4.83717042e-01],
       [4.14142209e-03, 9.08865071e-01, 8.69935065e-02],
       [9.84721529e-01, 1.52784299e-02, 4.11371092e-08],
       [9.74398931e-01, 2.56009681e-02, 1.00932996e-07],
       [1.23157103e-02, 8.95233371e-01, 9.24509190e-02],
       [2.03136213e-04, 1.81192395e-01, 8.18604469e-01],
       [9.80872460e-01, 1.91275146e-02, 2.49971225e-08],
       [5.14757725e-02, 9.01931458e-01, 4.65927696e-02],
       [1.22005053e-04, 1.76172450e-01, 8.23705545e-01],
       [1.23331076e-06, 2.21671608e-02, 9.77831606e-01],
       [1.11147861e-05, 3.25319546e-02, 9.67456931e-01],
       [9.68220109e-01, 3.17798495e-02, 4.12454448e-08],
       [9.88962740e-01, 1.10372

In [10]:
# 查看截距
clf.intercept_

clf.coef_

array([  9.63553225,   1.77023668, -11.40576893])

array([[-0.45745385,  0.82308704, -2.3134409 , -0.98424397],
       [ 0.50937705, -0.22432676, -0.18841994, -0.81164561],
       [-0.05192321, -0.59876028,  2.50186084,  1.79588959]])